project_id = "ffjipnkhcebjvttliptb"

[functions.telegram-invite-bot]
verify_jwt = false

[functions.telegram-announcer]
verify_jwt = false

[functions.news-fetcher]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.discord-interactions]
verify_jwt = false
