project_id = "ffjipnkhcebjvttliptb"

[functions.telegram-invite-bot]
verify_jwt = false

[functions.telegram-announcer]
verify_jwt = false

[functions.news-fetcher]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.discord-interactions]
verify_jwt = false

[functions.daily-digest]
verify_jwt = false

[functions.watch-checker]
verify_jwt = false

[functions.sync-bot-commands]
verify_jwt = false

[functions.alerts]
verify_jwt = true

[functions.alert-checker]
verify_jwt = false
