/**
 * CryptoCalendar — Real crypto news & events from RSS feeds + Jupiter trending.
 * Calendar view with event cards, reminders, and notifications.
 */
import { useState, useEffect, useMemo, useRef, useCallback } from "react";
import { Calendar, Clock, Bell, ChevronLeft, ChevronRight, Plus, Rocket, Unlock, Star, Users, ExternalLink, Trash2, Loader2, RefreshCw, Zap, Newspaper, Globe, Rss } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { jupTrending, fmtUsd, type JupTokenInfo } from "@/lib/og";

interface CalendarEvent {
  id: string;
  title: string;
  description: string;
  date: string;
  time?: string;
  type: "launch" | "unlock" | "ama" | "airdrop" | "custom" | "trending" | "news";
  tokenSymbol?: string;
  mint?: string;
  url?: string;
  source?: string;
  reminder: boolean;
  autoGenerated?: boolean;
}

const STORAGE_KEY = "ogscan_crypto_calendar";
const NEWS_CACHE_KEY = "ogscan_crypto_news_cache";
const NEWS_CACHE_TTL = 15 * 60 * 1000; // 15 minutes

const typeConfig: Record<string, { emoji: string; color: string; label: string }> = {
  launch: { emoji: "🚀", color: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20", label: "Launch" },
  unlock: { emoji: "🔓", color: "bg-amber-500/10 text-amber-400 border-amber-500/20", label: "Token Unlock" },
  ama: { emoji: "🎙️", color: "bg-blue-500/10 text-blue-400 border-blue-500/20", label: "AMA/Space" },
  airdrop: { emoji: "🎁", color: "bg-purple-500/10 text-purple-400 border-purple-500/20", label: "Airdrop" },
  trending: { emoji: "🔥", color: "bg-orange-500/10 text-orange-400 border-orange-500/20", label: "Trending" },
  news: { emoji: "📰", color: "bg-sky-500/10 text-sky-400 border-sky-500/20", label: "News" },
  custom: { emoji: "📌", color: "bg-white/[0.04] text-white/40 border-white/[0.08]", label: "Custom" },
};

/* ── RSS Feed Sources ── */
const RSS_FEEDS = [
  { name: "CoinDesk", url: "https://www.coindesk.com/arc/outboundfeeds/rss/" },
  { name: "CoinTelegraph", url: "https://cointelegraph.com/rss" },
  { name: "The Block", url: "https://www.theblock.co/rss.xml" },
  { name: "Decrypt", url: "https://decrypt.co/feed" },
];

/* ── RSS proxy via public CORS proxy ── */
async function fetchRSSFeed(feedUrl: string, feedName: string): Promise<CalendarEvent[]> {
  try {
    // Use a CORS proxy to fetch RSS from the browser
    const proxyUrl = `https://api.rss2json.com/v1/api.json?rss_url=${encodeURIComponent(feedUrl)}&count=10`;
    const res = await fetch(proxyUrl);
    if (!res.ok) return [];
    const data = await res.json();
    if (data.status !== "ok" || !data.items) return [];

    return data.items.slice(0, 8).map((item: any) => {
      const pubDate = new Date(item.pubDate || item.published || Date.now());
      const dateStr = pubDate.toISOString().split("T")[0];
      const timeStr = pubDate.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", hour12: false });

      // Extract clean title
      const title = (item.title || "").replace(/<[^>]+>/g, "").trim();
      const desc = (item.description || "")
        .replace(/<[^>]+>/g, "")
        .replace(/&[a-z]+;/gi, " ")
        .trim()
        .slice(0, 160);

      return {
        id: `news-${feedName}-${item.guid || item.link || title}`,
        title: title || "Crypto News",
        description: desc || `From ${feedName}`,
        date: dateStr,
        time: timeStr,
        type: "news" as const,
        url: item.link,
        source: feedName,
        reminder: false,
        autoGenerated: true,
      };
    });
  } catch (e) {
    console.error(`[CryptoCalendar] Failed to fetch ${feedName}:`, e);
    return [];
  }
}

function loadEvents(): CalendarEvent[] {
  try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]"); } catch { return []; }
}
function saveEvents(events: CalendarEvent[]) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(events));
}

function getCachedNews(): { items: CalendarEvent[]; ts: number } | null {
  try {
    const raw = localStorage.getItem(NEWS_CACHE_KEY);
    if (!raw) return null;
    const cached = JSON.parse(raw);
    if (Date.now() - cached.ts > NEWS_CACHE_TTL) return null;
    return cached;
  } catch { return null; }
}

function cacheNews(items: CalendarEvent[]) {
  localStorage.setItem(NEWS_CACHE_KEY, JSON.stringify({ items, ts: Date.now() }));
}

export const CryptoCalendar: React.FC = () => {
  const [events, setEvents] = useState<CalendarEvent[]>(loadEvents);
  const [currentMonth, setCurrentMonth] = useState(new Date());
  const [showAddEvent, setShowAddEvent] = useState(false);
  const [newEvent, setNewEvent] = useState<Partial<CalendarEvent>>({ type: "custom", reminder: false });
  const [view, setView] = useState<"calendar" | "list">("list");
  const [loading, setLoading] = useState(false);
  const [feedFilter, setFeedFilter] = useState<"all" | "news" | "trending" | "custom">("all");
  const mounted = useRef(true);
  useEffect(() => () => { mounted.current = false; }, []);

  const monthStr = currentMonth.toLocaleDateString("en-US", { month: "long", year: "numeric" });
  const prevMonth = () => setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() - 1));
  const nextMonth = () => setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1));

  /* ── Fetch real news from RSS feeds ── */
  const fetchNews = useCallback(async () => {
    // Check cache first
    const cached = getCachedNews();
    if (cached) {
      mergeAutoEvents(cached.items);
      return;
    }

    setLoading(true);
    try {
      const results = await Promise.allSettled(
        RSS_FEEDS.map(f => fetchRSSFeed(f.url, f.name))
      );
      const allNews: CalendarEvent[] = [];
      for (const r of results) {
        if (r.status === "fulfilled") allNews.push(...r.value);
      }

      // Sort by date descending, deduplicate by title
      const seen = new Set<string>();
      const unique = allNews
        .sort((a, b) => b.date.localeCompare(a.date))
        .filter(e => {
          const key = e.title.toLowerCase().slice(0, 60);
          if (seen.has(key)) return false;
          seen.add(key);
          return true;
        })
        .slice(0, 30);

      cacheNews(unique);
      mergeAutoEvents(unique);
    } catch (e) {
      console.error("[CryptoCalendar] RSS fetch error:", e);
    }
    if (mounted.current) setLoading(false);
  }, []);

  /* ── Fetch trending token events (Jupiter) ── */
  const fetchTrendingEvents = useCallback(async () => {
    try {
      const trending = await jupTrending("1h", 10);
      if (!mounted.current) return;

      const today = new Date().toISOString().split("T")[0];
      const now = new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", hour12: false });

      const trendingEvents: CalendarEvent[] = trending
        .slice(0, 5)
        .map(t => {
          const mint = (t as any).address ?? t.id;
          const change = t.stats1h?.priceChange ?? t.stats24h?.priceChange ?? 0;
          return {
            id: `auto-${mint}-${today}`,
            title: `$${t.symbol} trending ${change >= 0 ? "+" : ""}${change.toFixed(0)}%`,
            description: `MCap: ${fmtUsd(t.mcap ?? 0)} · LP: ${fmtUsd(t.liquidity ?? 0)}`,
            date: today,
            time: now,
            type: "trending" as const,
            tokenSymbol: t.symbol,
            mint,
            reminder: false,
            autoGenerated: true,
          };
        });

      mergeAutoEvents(trendingEvents);
    } catch (e) {
      console.error("[CryptoCalendar] Trending fetch error:", e);
    }
  }, []);

  /* ── Merge auto-generated events with manual ones ── */
  const mergeAutoEvents = (newAuto: CalendarEvent[]) => {
    setEvents(prev => {
      const today = new Date().toISOString().split("T")[0];
      // Keep manual events and fresh auto events
      const manual = prev.filter(e => !e.autoGenerated);
      const existingIds = new Set(manual.map(e => e.id));

      // Deduplicate auto events
      const autoToAdd = newAuto.filter(e => !existingIds.has(e.id));

      // Remove old trending (older than today), keep old news for 3 days
      const threeDaysAgo = new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split("T")[0];
      const oldAuto = prev.filter(
        e => e.autoGenerated && !existingIds.has(e.id) && !newAuto.some(n => n.id === e.id)
          && (e.type === "news" ? e.date >= threeDaysAgo : e.date >= today)
      );

      const merged = [...manual, ...oldAuto, ...autoToAdd]
        .sort((a, b) => b.date.localeCompare(a.date) || (b.time || "").localeCompare(a.time || ""));
      saveEvents(merged);
      return merged;
    });
  };

  // Fetch on mount
  useEffect(() => {
    fetchNews();
    fetchTrendingEvents();
  }, [fetchNews, fetchTrendingEvents]);

  const addCustomEvent = () => {
    if (!newEvent.title || !newEvent.date) { toast.error("Title and date required"); return; }
    const ev: CalendarEvent = {
      id: `custom-${Date.now()}`,
      title: newEvent.title!,
      description: newEvent.description || "",
      date: newEvent.date!,
      time: newEvent.time,
      type: newEvent.type as CalendarEvent["type"] || "custom",
      url: newEvent.url,
      reminder: newEvent.reminder || false,
    };
    const updated = [ev, ...events].sort((a, b) => b.date.localeCompare(a.date));
    setEvents(updated);
    saveEvents(updated);
    setNewEvent({ type: "custom", reminder: false });
    setShowAddEvent(false);
    toast.success("Event added");
  };

  const deleteEvent = (id: string) => {
    const updated = events.filter(e => e.id !== id);
    setEvents(updated);
    saveEvents(updated);
    toast.success("Event removed");
  };

  const filteredEvents = useMemo(() => {
    if (feedFilter === "all") return events;
    if (feedFilter === "news") return events.filter(e => e.type === "news");
    if (feedFilter === "trending") return events.filter(e => e.type === "trending");
    return events.filter(e => !e.autoGenerated);
  }, [events, feedFilter]);

  // Calendar grid
  const calendarDays = useMemo(() => {
    const y = currentMonth.getFullYear(), m = currentMonth.getMonth();
    const first = new Date(y, m, 1);
    const last = new Date(y, m + 1, 0);
    const startOffset = first.getDay();
    const days: { date: string; day: number; inMonth: boolean; events: CalendarEvent[] }[] = [];
    for (let i = -startOffset; i <= last.getDate() + (6 - last.getDay()); i++) {
      const d = new Date(y, m, i + 1);
      const ds = d.toISOString().split("T")[0];
      days.push({
        date: ds,
        day: d.getDate(),
        inMonth: d.getMonth() === m,
        events: events.filter(e => e.date === ds),
      });
    }
    return days;
  }, [currentMonth, events]);

  const newsCount = events.filter(e => e.type === "news").length;
  const trendingCount = events.filter(e => e.type === "trending").length;
  const customCount = events.filter(e => !e.autoGenerated).length;

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 rounded-2xl border border-white/[0.07] bg-white/[0.02] p-4">
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-xl border border-og-cyan/20 bg-og-cyan/5 flex items-center justify-center">
            <Calendar className="h-5 w-5 text-og-cyan" />
          </div>
          <div>
            <h3 className="text-sm font-black uppercase tracking-wider text-white">Crypto Calendar</h3>
            <p className="text-[10px] uppercase tracking-widest text-white/30">Live news · Trending · Events</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <div className="flex gap-1 p-1 rounded-xl bg-white/[0.03] border border-white/[0.06]">
            {(["all", "news", "trending", "custom"] as const).map(f => (
              <button key={f} onClick={() => setFeedFilter(f)}
                className={cn("px-3 py-1.5 rounded-lg text-[9px] font-black uppercase tracking-widest transition-all",
                  feedFilter === f ? "bg-og-cyan/15 text-og-cyan" : "text-white/25 hover:text-white/40")}>
                {f === "all" ? `All (${events.length})` : f === "news" ? `News (${newsCount})` : f === "trending" ? `Trending (${trendingCount})` : `Custom (${customCount})`}
              </button>
            ))}
          </div>
          <button onClick={() => setView(view === "list" ? "calendar" : "list")}
            className="p-2 rounded-xl border border-white/[0.08] bg-white/[0.03] text-white/30 hover:text-white transition-all">
            <Calendar className="h-4 w-4" />
          </button>
          <button onClick={() => { fetchNews(); fetchTrendingEvents(); }} disabled={loading}
            className="p-2 rounded-xl border border-white/[0.08] bg-white/[0.03] text-white/30 hover:text-white transition-all disabled:opacity-50">
            <RefreshCw className={cn("h-4 w-4", loading && "animate-spin")} />
          </button>
          <button onClick={() => setShowAddEvent(!showAddEvent)}
            className="p-2 rounded-xl bg-og-cyan/10 border border-og-cyan/20 text-og-cyan hover:bg-og-cyan/20 transition-all">
            <Plus className="h-4 w-4" />
          </button>
        </div>
      </div>

      {/* Add Event Form */}
      {showAddEvent && (
        <div className="rounded-2xl border border-og-cyan/20 bg-og-cyan/5 p-4 space-y-3">
          <p className="text-[10px] font-black text-og-cyan uppercase tracking-widest">Add Custom Event</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <Input placeholder="Event title" value={newEvent.title || ""} onChange={e => setNewEvent(p => ({ ...p, title: e.target.value }))}
              className="bg-white/5 border-white/10 text-sm" />
            <Input type="date" value={newEvent.date || ""} onChange={e => setNewEvent(p => ({ ...p, date: e.target.value }))}
              className="bg-white/5 border-white/10 text-sm" />
            <Input placeholder="Description" value={newEvent.description || ""} onChange={e => setNewEvent(p => ({ ...p, description: e.target.value }))}
              className="bg-white/5 border-white/10 text-sm" />
            <Input placeholder="URL (optional)" value={newEvent.url || ""} onChange={e => setNewEvent(p => ({ ...p, url: e.target.value }))}
              className="bg-white/5 border-white/10 text-sm" />
          </div>
          <div className="flex items-center gap-2">
            <select value={newEvent.type} onChange={e => setNewEvent(p => ({ ...p, type: e.target.value as CalendarEvent["type"] }))}
              className="h-9 px-3 rounded-lg bg-white/5 border border-white/10 text-xs text-white">
              {Object.entries(typeConfig).filter(([k]) => k !== "news").map(([k, v]) => (
                <option key={k} value={k}>{v.emoji} {v.label}</option>
              ))}
            </select>
            <Button size="sm" onClick={addCustomEvent} className="bg-og-cyan text-[#070d14] font-black text-xs px-4">Add</Button>
            <Button size="sm" variant="ghost" onClick={() => setShowAddEvent(false)} className="text-white/30 text-xs">Cancel</Button>
          </div>
        </div>
      )}

      {/* Calendar Grid View */}
      {view === "calendar" && (
        <div className="rounded-2xl border border-white/[0.07] bg-white/[0.02] p-4">
          <div className="flex items-center justify-between mb-4">
            <button onClick={prevMonth} className="p-1.5 rounded-lg hover:bg-white/[0.04]"><ChevronLeft className="h-4 w-4 text-white/40" /></button>
            <span className="text-sm font-black text-white uppercase tracking-widest">{monthStr}</span>
            <button onClick={nextMonth} className="p-1.5 rounded-lg hover:bg-white/[0.04]"><ChevronRight className="h-4 w-4 text-white/40" /></button>
          </div>
          <div className="grid grid-cols-7 gap-1">
            {["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map(d => (
              <div key={d} className="text-center text-[8px] font-black text-white/20 uppercase tracking-widest py-1">{d}</div>
            ))}
            {calendarDays.map(d => (
              <div key={d.date} className={cn("h-12 rounded-lg p-1 text-[10px] relative",
                d.inMonth ? "bg-white/[0.02]" : "opacity-30",
                d.events.length > 0 && "ring-1 ring-og-cyan/20")}>
                <span className="text-white/40">{d.day}</span>
                {d.events.length > 0 && (
                  <div className="absolute bottom-1 left-1 flex gap-0.5">
                    {d.events.slice(0, 3).map((e, i) => (
                      <div key={i} className={cn("h-1.5 w-1.5 rounded-full",
                        e.type === "news" ? "bg-sky-400" : e.type === "trending" ? "bg-orange-400" : "bg-og-cyan")} />
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* List View */}
      {view === "list" && (
        <div className="rounded-2xl border border-white/[0.07] bg-white/[0.02] divide-y divide-white/[0.04] overflow-hidden">
          {loading && events.length === 0 ? (
            <div className="flex items-center justify-center py-16">
              <Loader2 className="h-6 w-6 text-og-cyan animate-spin" />
            </div>
          ) : filteredEvents.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-16">
              <Newspaper className="h-8 w-8 text-white/10 mb-3" />
              <p className="text-xs text-white/30 font-bold uppercase">No events found</p>
            </div>
          ) : (
            filteredEvents.slice(0, 50).map(e => {
              const cfg = typeConfig[e.type] || typeConfig.custom;
              return (
                <div key={e.id} className="flex items-start gap-3 p-4 hover:bg-white/[0.02] transition-colors group">
                  <div className="shrink-0 mt-0.5">
                    <Badge className={cn("text-[9px] font-black border px-2 py-0.5", cfg.color)}>
                      {cfg.emoji} {cfg.label}
                    </Badge>
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-bold text-white/80 leading-tight line-clamp-2">{e.title}</p>
                    <p className="text-[10px] text-white/30 mt-1 line-clamp-2">{e.description}</p>
                    <div className="flex items-center gap-3 mt-1.5 text-[9px] text-white/20">
                      <span className="flex items-center gap-1"><Clock className="h-3 w-3" />{e.date}{e.time ? ` · ${e.time}` : ""}</span>
                      {e.source && <span className="flex items-center gap-1"><Rss className="h-3 w-3" />{e.source}</span>}
                      {e.tokenSymbol && <Badge variant="outline" className="text-[8px] border-orange-500/20 text-orange-400">${e.tokenSymbol}</Badge>}
                    </div>
                  </div>
                  <div className="flex items-center gap-1 shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">
                    {e.url && (
                      <a href={e.url} target="_blank" rel="noreferrer"
                        className="p-1.5 rounded-lg hover:bg-white/[0.06] text-white/20 hover:text-white transition-colors">
                        <ExternalLink className="h-3.5 w-3.5" />
                      </a>
                    )}
                    <button onClick={() => deleteEvent(e.id)}
                      className="p-1.5 rounded-lg hover:bg-red-400/10 text-white/10 hover:text-red-400 transition-colors">
                      <Trash2 className="h-3.5 w-3.5" />
                    </button>
                  </div>
                </div>
              );
            })
          )}
        </div>
      )}

      {/* RSS Sources */}
      <div className="rounded-2xl border border-white/[0.07] bg-white/[0.02] p-4">
        <div className="flex items-center gap-2 mb-3">
          <Rss className="h-4 w-4 text-sky-400" />
          <span className="text-[10px] font-black text-white/40 uppercase tracking-widest">News Sources</span>
        </div>
        <div className="flex flex-wrap gap-2">
          {RSS_FEEDS.map(f => (
            <div key={f.name} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-sky-500/5 border border-sky-500/10">
              <Globe className="h-3 w-3 text-sky-400" />
              <span className="text-[9px] font-black text-sky-400/70 uppercase tracking-widest">{f.name}</span>
            </div>
          ))}
          <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-orange-500/5 border border-orange-500/10">
            <Zap className="h-3 w-3 text-orange-400" />
            <span className="text-[9px] font-black text-orange-400/70 uppercase tracking-widest">Jupiter Trending</span>
          </div>
        </div>
      </div>
    </div>
  );
};
