/**
 * IntelFeed — News, KOL Scanner, and Calendar in a compact tabbed component.
 * Redesigned: fixed-height scrollable panels, DB-backed, 25 items per category.
 */
import { useState, useEffect, useMemo, useRef, useCallback } from "react";
import {
  Newspaper, Users, Calendar, RefreshCw, ExternalLink, Plus, Trash2,
  Loader2, TrendingUp, TrendingDown, Clock, ChevronLeft, ChevronRight,
  Wallet, ArrowUpRight, ArrowDownRight, AlertCircle, Zap, Star,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { supabase } from "@/lib/supabase";
import { jupTrending, fmtUsd } from "@/lib/og";

/* ─────────────────────────────────────────────────────────────── */
/* Types                                                            */
/* ─────────────────────────────────────────────────────────────── */

interface NewsItem {
  id: string;
  title: string;
  description?: string | null;
  source: string;
  category: string;
  sentiment?: string | null;
  published_at: string;
  source_url?: string | null;
  image_url?: string | null;
  is_featured?: boolean | null;
  engagement_score?: number | null;
  // RSS-only
  fromRss?: boolean;
}

interface KolProfile {
  id: string;
  name: string;
  x_handle?: string | null;
  bio?: string | null;
  image_url?: string | null;
  followers_count?: number | null;
  wallet_address?: string | null;
  blockchain?: string | null;
  is_active?: boolean | null;
}

interface KolHolding {
  id: string;
  kol_id: string;
  token_address: string;
  symbol: string;
  name?: string | null;
  balance: number;
  value_usd: number;
  pnl_usd: number;
  pnl_pct: number;
  current_price?: number | null;
  avg_buy_price?: number | null;
}

interface KolTransaction {
  id: string;
  kol_id: string;
  tx_type: string;
  symbol_in?: string | null;
  symbol_out?: string | null;
  amount_in?: number | null;
  amount_out?: number | null;
  price_usd?: number | null;
  tx_timestamp: string;
  kolName?: string;
  kolHandle?: string;
}

interface CalEvent {
  id: string;
  title: string;
  description: string;
  date: string;
  time?: string;
  type: "launch" | "unlock" | "ama" | "airdrop" | "custom" | "trending" | "news";
  tokenSymbol?: string;
  mint?: string;
  url?: string;
  source?: string;
  reminder: boolean;
  autoGenerated?: boolean;
}

/* ─────────────────────────────────────────────────────────────── */
/* Constants                                                        */
/* ─────────────────────────────────────────────────────────────── */

const CAL_STORAGE_KEY = "ogscan_intel_calendar_v2";
const NEWS_CACHE_KEY = "ogscan_intel_news_v2";
const NEWS_CACHE_TTL = 15 * 60 * 1000;
const MAX_PER_CATEGORY = 40;
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmamlwbmtoY2VianZ0dGxpcHRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1Mjc5NDgsImV4cCI6MjA5MzEwMzk0OH0.***REMOVED_ANON_SIG***";
const EDGE_NEWS_URL = "https://ffjipnkhcebjvttliptb.supabase.co/functions/v1/news-fetcher";

const RSS_FEEDS = [
  { name: "CoinTelegraph", url: "https://cointelegraph.com/rss" },
  { name: "CoinDesk", url: "https://www.coindesk.com/arc/outboundfeeds/rss/" },
  { name: "Decrypt", url: "https://decrypt.co/feed" },
  { name: "The Block", url: "https://www.theblock.co/rss.xml" },
];

const sentimentConfig = {
  bullish: { label: "Bullish", cls: "text-og-lime border-og-lime/30 bg-og-lime/10" },
  bearish: { label: "Bearish", cls: "text-red-400 border-red-400/30 bg-red-400/10" },
  neutral: { label: "Neutral", cls: "text-white/40 border-white/10 bg-white/5" },
};

const eventTypeConfig: Record<string, { emoji: string; color: string; label: string }> = {
  launch: { emoji: "🚀", color: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20", label: "Launch" },
  unlock: { emoji: "🔓", color: "bg-amber-500/10 text-amber-400 border-amber-500/20", label: "Token Unlock" },
  ama: { emoji: "🎙️", color: "bg-blue-500/10 text-blue-400 border-blue-500/20", label: "AMA/Space" },
  airdrop: { emoji: "🎁", color: "bg-purple-500/10 text-purple-400 border-purple-500/20", label: "Airdrop" },
  trending: { emoji: "🔥", color: "bg-orange-500/10 text-orange-400 border-orange-500/20", label: "Trending" },
  news: { emoji: "📰", color: "bg-sky-500/10 text-sky-400 border-sky-500/20", label: "News" },
  custom: { emoji: "📌", color: "bg-white/[0.04] text-white/40 border-white/[0.08]", label: "Custom" },
};

/* ─────────────────────────────────────────────────────────────── */
/* Helpers                                                          */
/* ─────────────────────────────────────────────────────────────── */

function fmtRelTime(dateStr: string): string {
  const diff = Date.now() - new Date(dateStr).getTime();
  const m = Math.floor(diff / 60000);
  if (m < 1) return "just now";
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

function fmtK(n?: number | null): string {
  if (!n) return "0";
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return String(n);
}

function loadCalEvents(): CalEvent[] {
  try { return JSON.parse(localStorage.getItem(CAL_STORAGE_KEY) || "[]"); } catch { return []; }
}
function saveCalEvents(ev: CalEvent[]) {
  localStorage.setItem(CAL_STORAGE_KEY, JSON.stringify(ev));
}
function getCachedNews(): { items: NewsItem[]; ts: number } | null {
  try { const raw = localStorage.getItem(NEWS_CACHE_KEY); return raw ? JSON.parse(raw) : null; } catch { return null; }
}
function setCachedNews(items: NewsItem[]) {
  localStorage.setItem(NEWS_CACHE_KEY, JSON.stringify({ items, ts: Date.now() }));
}

async function fetchRSSNews(): Promise<NewsItem[]> {
  const all: NewsItem[] = [];
  await Promise.allSettled(RSS_FEEDS.map(async ({ name, url }) => {
    try {
      const res = await fetch(`https://api.rss2json.com/v1/api.json?rss_url=${encodeURIComponent(url)}&count=8`);
      if (!res.ok) return;
      const data = await res.json();
      if (data.status !== "ok" || !data.items) return;
      for (const item of data.items.slice(0, 8)) {
        const title = (item.title || "").replace(/<[^>]+>/g, "").trim();
        if (!title) continue;
        all.push({
          id: `rss-${name}-${item.guid || item.link || title}`.slice(0, 120),
          title,
          description: (item.description || "").replace(/<[^>]+>/g, "").replace(/&[a-z]+;/gi, " ").trim().slice(0, 200),
          source: name,
          category: "news",
          published_at: new Date(item.pubDate || Date.now()).toISOString(),
          source_url: item.link || null,
          fromRss: true,
        });
      }
    } catch { /* noop */ }
  }));
  return all;
}

/* ─────────────────────────────────────────────────────────────── */
/* Sub-components                                                   */
/* ─────────────────────────────────────────────────────────────── */

/* ── Scrollable news card ── */
function NewsCard({ item }: { item: NewsItem }) {
  const sent = item.sentiment?.toLowerCase() as keyof typeof sentimentConfig | undefined;
  const sentCfg = sent && sentimentConfig[sent] ? sentimentConfig[sent] : null;
  return (
    <a
      href={item.source_url || "#"}
      target="_blank"
      rel="noopener noreferrer"
      className="group block rounded-[1.1rem] border border-white/[0.06] bg-white/[0.02] p-3.5 transition hover:bg-white/[0.04] hover:border-white/[0.1] active:scale-[0.99]"
    >
      <div className="flex items-start justify-between gap-2 mb-1.5">
        <div className="flex items-center gap-1.5 flex-wrap">
          {item.is_featured && (
            <span className="flex items-center gap-0.5 rounded-md px-1.5 py-0.5 text-[9px] font-black uppercase tracking-widest border border-og-gold/30 bg-og-gold/10 text-og-gold">
              <Star className="h-2.5 w-2.5" /> Featured
            </span>
          )}
          <span className="rounded-md px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-widest border border-white/10 bg-white/5 text-white/40">
            {item.source}
          </span>
          {sentCfg && (
            <span className={cn("rounded-md px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-widest border", sentCfg.cls)}>
              {sentCfg.label}
            </span>
          )}
        </div>
        <ExternalLink className="h-3.5 w-3.5 shrink-0 text-white/20 group-hover:text-white/50 transition mt-0.5" />
      </div>
      <p className="text-[13px] font-bold text-white leading-snug line-clamp-2 mb-1">{item.title}</p>
      {item.description && (
        <p className="text-[11px] text-white/40 leading-relaxed line-clamp-2">{item.description}</p>
      )}
      <p className="mt-2 text-[10px] text-white/25">{fmtRelTime(item.published_at)}</p>
    </a>
  );
}

/* ── KOL profile row ── */
function KolRow({ kol, holdings }: { kol: KolProfile; holdings: KolHolding[] }) {
  const [expanded, setExpanded] = useState(false);
  const totalValue = holdings.reduce((s, h) => s + Number(h.value_usd), 0);
  const totalPnl = holdings.reduce((s, h) => s + Number(h.pnl_usd), 0);
  const initials = kol.name?.slice(0, 2).toUpperCase() || "KL";

  return (
    <div className="rounded-[1.1rem] border border-white/[0.06] bg-white/[0.02] overflow-hidden">
      <button
        type="button"
        className="w-full flex items-center gap-3 p-3.5 text-left transition hover:bg-white/[0.03]"
        onClick={() => setExpanded(e => !e)}
      >
        {/* avatar */}
        {kol.image_url ? (
          <img src={kol.image_url} alt="" className="h-10 w-10 rounded-xl object-cover border border-white/10 shrink-0" />
        ) : (
          <div className="h-10 w-10 rounded-xl border border-primary/25 bg-primary/10 flex items-center justify-center text-[11px] font-black text-primary shrink-0">
            {initials}
          </div>
        )}
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-1.5">
            <span className="text-[13px] font-black text-white truncate">{kol.name}</span>
            {kol.is_active && <span className="h-1.5 w-1.5 rounded-full bg-og-lime shrink-0" />}
          </div>
          <p className="text-[11px] text-white/40 truncate">{kol.x_handle || kol.blockchain || "KOL"}</p>
        </div>
        <div className="shrink-0 text-right">
          {totalValue > 0 ? (
            <>
              <p className="text-[12px] font-black text-white">{fmtUsd(totalValue)}</p>
              <p className={cn("text-[10px] font-bold", totalPnl >= 0 ? "text-og-lime" : "text-red-400")}>
                {totalPnl >= 0 ? "+" : ""}{fmtUsd(totalPnl)}
              </p>
            </>
          ) : (
            <span className="text-[11px] text-white/25">{fmtK(kol.followers_count)} followers</span>
          )}
        </div>
        <ChevronRight className={cn("h-4 w-4 text-white/25 transition shrink-0 ml-1", expanded && "rotate-90")} />
      </button>

      {expanded && (
        <div className="px-3.5 pb-3.5 space-y-2 border-t border-white/[0.05]">
          {/* wallet */}
          {kol.wallet_address && (
            <div className="flex items-center gap-2 pt-2">
              <Wallet className="h-3.5 w-3.5 text-white/30 shrink-0" />
              <span className="font-mono text-[11px] text-white/40 truncate">{kol.wallet_address}</span>
            </div>
          )}
          {/* holdings */}
          {holdings.length > 0 ? (
            <div className="space-y-1.5 pt-1">
              <p className="text-[10px] font-black text-white/30 uppercase tracking-widest">Holdings</p>
              {holdings.map(h => (
                <div key={h.id} className="flex items-center justify-between gap-2 rounded-xl border border-white/[0.05] bg-white/[0.02] px-3 py-2">
                  <div>
                    <p className="text-[12px] font-black text-white">{h.symbol}</p>
                    <p className="text-[10px] text-white/35">{Number(h.balance).toLocaleString(undefined, { maximumFractionDigits: 2 })}</p>
                  </div>
                  <div className="text-right">
                    <p className="text-[12px] font-bold text-white">{fmtUsd(h.value_usd)}</p>
                    <p className={cn("text-[10px] font-bold flex items-center justify-end gap-0.5", Number(h.pnl_pct) >= 0 ? "text-og-lime" : "text-red-400")}>
                      {Number(h.pnl_pct) >= 0 ? <TrendingUp className="h-3 w-3" /> : <TrendingDown className="h-3 w-3" />}
                      {Number(h.pnl_pct) >= 0 ? "+" : ""}{Number(h.pnl_pct).toFixed(1)}%
                    </p>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-[11px] text-white/25 pt-2">No holdings tracked yet</p>
          )}
        </div>
      )}
    </div>
  );
}

/* ── Calendar event row ── */
function CalEventRow({ ev, onDelete }: { ev: CalEvent; onDelete: (id: string) => void }) {
  const cfg = eventTypeConfig[ev.type] || eventTypeConfig.custom;
  return (
    <div className="group flex items-start gap-3 rounded-[1.1rem] border border-white/[0.06] bg-white/[0.02] p-3.5">
      <span className="text-xl mt-0.5 shrink-0">{cfg.emoji}</span>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-1.5 flex-wrap mb-0.5">
          <span className={cn("rounded-md px-1.5 py-0.5 text-[9px] font-black uppercase tracking-widest border", cfg.color)}>
            {cfg.label}
          </span>
          {ev.source && (
            <span className="text-[9px] text-white/30">{ev.source}</span>
          )}
        </div>
        <p className="text-[13px] font-bold text-white leading-snug line-clamp-2">{ev.title}</p>
        {ev.description && <p className="text-[11px] text-white/40 line-clamp-1 mt-0.5">{ev.description}</p>}
        <div className="flex items-center gap-2 mt-1.5">
          <Clock className="h-3 w-3 text-white/25" />
          <span className="text-[10px] text-white/30">{ev.date}{ev.time ? ` · ${ev.time}` : ""}</span>
          {ev.url && (
            <a href={ev.url} target="_blank" rel="noopener noreferrer" className="ml-auto">
              <ExternalLink className="h-3 w-3 text-white/25 hover:text-white/60 transition" />
            </a>
          )}
        </div>
      </div>
      {!ev.autoGenerated && (
        <button
          type="button"
          onClick={() => onDelete(ev.id)}
          className="opacity-0 group-hover:opacity-100 transition shrink-0 mt-0.5"
        >
          <Trash2 className="h-3.5 w-3.5 text-white/25 hover:text-red-400 transition" />
        </button>
      )}
    </div>
  );
}

/* ─────────────────────────────────────────────────────────────── */
/* Main Component                                                   */
/* ─────────────────────────────────────────────────────────────── */

type Tab = "news" | "calendar";
type KolFilter = "all" | "buys" | "sells" | "holdings";
type CalFilter = "all" | "news" | "trending" | "custom";

export function CryptoCalendar() {
  const [tab, setTab] = useState<Tab>("news");

  /* ── News state ── */
  const [news, setNews] = useState<NewsItem[]>([]);
  const [newsLoading, setNewsLoading] = useState(true);
  const [newsFilter, setNewsFilter] = useState<string>("all");

  /* ── KOL state ── */
  const [kols, setKols] = useState<KolProfile[]>([]);
  const [holdings, setHoldings] = useState<Record<string, KolHolding[]>>({});
  const [transactions, setTransactions] = useState<KolTransaction[]>([]);
  const [kolLoading, setKolLoading] = useState(false);
  const [kolFilter, setKolFilter] = useState<KolFilter>("all");

  /* ── Calendar state ── */
  const [calEvents, setCalEvents] = useState<CalEvent[]>(loadCalEvents);
  const [calFilter, setCalFilter] = useState<CalFilter>("all");
  const [showAddForm, setShowAddForm] = useState(false);
  const [newEvent, setNewEvent] = useState<Partial<CalEvent>>({ type: "custom", reminder: false });
  const [calLoading, setCalLoading] = useState(false);

  const mounted = useRef(true);
  useEffect(() => { return () => { mounted.current = false; }; }, []);

  /* ─── Fetch News ─── */
  const loadNews = useCallback(async (force = false) => {
    setNewsLoading(true);
    try {
      // 1. Try DB first
      const { data: dbNews } = await supabase
        .from("crypto_news")
        .select("id, title, description, source, category, sentiment, published_at, source_url, image_url, is_featured, engagement_score")
        .order("published_at", { ascending: false })
        .limit(MAX_PER_CATEGORY);

      if (dbNews && dbNews.length > 0) {
        if (mounted.current) setNews(dbNews as NewsItem[]);
        setNewsLoading(false);
        return;
      }

      // 2. DB is empty — trigger edge function to populate it
      try {
        await fetch(EDGE_NEWS_URL, {
          method: "POST",
          headers: { "Authorization": `Bearer ${SUPABASE_ANON_KEY}`, "Content-Type": "application/json" },
          body: "{}",
        });
        // Re-fetch from DB after edge function runs
        const { data: freshNews } = await supabase
          .from("crypto_news")
          .select("id, title, description, source, category, sentiment, published_at, source_url, image_url, is_featured, engagement_score")
          .order("published_at", { ascending: false })
          .limit(MAX_PER_CATEGORY);
        if (freshNews && freshNews.length > 0) {
          if (mounted.current) setNews(freshNews as NewsItem[]);
          setNewsLoading(false);
          return;
        }
      } catch (_) { /* noop — fall through to RSS */ }

      // 3. Fall back to RSS with cache
      const cached = getCachedNews();
      if (!force && cached && Date.now() - cached.ts < NEWS_CACHE_TTL) {
        if (mounted.current) { setNews(cached.items); setNewsLoading(false); }
        return;
      }

      const rssItems = await fetchRSSNews();
      const seen = new Set<string>();
      const deduped = rssItems
        .sort((a, b) => new Date(b.published_at).getTime() - new Date(a.published_at).getTime())
        .filter(item => {
          const key = item.title.toLowerCase().slice(0, 60);
          if (seen.has(key)) return false;
          seen.add(key);
          return true;
        })
        .slice(0, MAX_PER_CATEGORY);

      setCachedNews(deduped);
      if (mounted.current) setNews(deduped);
    } catch (e) {
      console.error("[IntelFeed] News error:", e);
    }
    if (mounted.current) setNewsLoading(false);
  }, []);

  /* ─── Fetch KOL data ─── */
  const loadKols = useCallback(async () => {
    if (kols.length > 0) return; // already loaded
    setKolLoading(true);
    try {
      const { data: kolData } = await supabase
        .from("kol_profiles")
        .select("id, name, x_handle, bio, image_url, followers_count, wallet_address, blockchain, is_active")
        .order("followers_count", { ascending: false, nullsFirst: false })
        .limit(MAX_PER_CATEGORY);

      if (!mounted.current || !kolData) return;
      setKols(kolData as KolProfile[]);

      // Fetch holdings for each KOL
      const kolIds = kolData.map((k: KolProfile) => k.id);
      if (kolIds.length > 0) {
        const { data: holdingsData } = await supabase
          .from("kol_holdings")
          .select("id, kol_id, token_address, symbol, name, balance, value_usd, pnl_usd, pnl_pct, current_price, avg_buy_price")
          .in("kol_id", kolIds)
          .order("value_usd", { ascending: false });

        if (holdingsData && mounted.current) {
          const byKol: Record<string, KolHolding[]> = {};
          for (const h of holdingsData as KolHolding[]) {
            if (!byKol[h.kol_id]) byKol[h.kol_id] = [];
            byKol[h.kol_id].push(h);
          }
          setHoldings(byKol);
        }

        // Fetch recent transactions
        const { data: txData } = await supabase
          .from("kol_transactions")
          .select("id, kol_id, tx_type, symbol_in, symbol_out, amount_in, amount_out, price_usd, tx_timestamp")
          .in("kol_id", kolIds)
          .order("tx_timestamp", { ascending: false })
          .limit(50);

        if (txData && mounted.current) {
          const kolMap: Record<string, KolProfile> = {};
          for (const k of kolData as KolProfile[]) kolMap[k.id] = k;
          setTransactions((txData as KolTransaction[]).map(tx => ({
            ...tx,
            kolName: kolMap[tx.kol_id]?.name,
            kolHandle: kolMap[tx.kol_id]?.x_handle || undefined,
          })));
        }
      }
    } catch (e) {
      console.error("[IntelFeed] KOL error:", e);
    }
    if (mounted.current) setKolLoading(false);
  }, [kols.length]);

  /* ─── Fetch Calendar trending ─── */
  const loadTrending = useCallback(async () => {
    setCalLoading(true);
    try {
      const trending = await jupTrending("1h", 10);
      const today = new Date().toISOString().split("T")[0];
      const now = new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", hour12: false });
      const trendEvents: CalEvent[] = trending.slice(0, 5).map(t => {
        const mint = (t as any).address ?? t.id;
        const change = t.stats1h?.priceChange ?? t.stats24h?.priceChange ?? 0;
        return {
          id: `trend-${mint}-${today}`,
          title: `$${t.symbol} trending ${change >= 0 ? "+" : ""}${change.toFixed(0)}%`,
          description: `MCap: ${fmtUsd(t.mcap ?? 0)} · LP: ${fmtUsd(t.liquidity ?? 0)}`,
          date: today, time: now, type: "trending", tokenSymbol: t.symbol, mint,
          reminder: false, autoGenerated: true,
        };
      });
      if (mounted.current) {
        setCalEvents(prev => {
          const manual = prev.filter(e => !e.autoGenerated);
          const seen = new Set(manual.map(e => e.id));
          const merged = [...manual, ...trendEvents.filter(e => !seen.has(e.id))]
            .sort((a, b) => b.date.localeCompare(a.date) || (b.time || "").localeCompare(a.time || ""));
          saveCalEvents(merged);
          return merged;
        });
      }
    } catch { /* noop */ }
    if (mounted.current) setCalLoading(false);
  }, []);

  /* Load on tab activation */
  useEffect(() => {
    if (tab === "news") loadNews();
    // kol tab removed
    if (tab === "calendar") loadTrending();
  }, [tab, loadNews, loadKols, loadTrending]);

  /* ─── Calendar helpers ─── */
  const addCalEvent = () => {
    if (!newEvent.title || !newEvent.date) { toast.error("Title and date required"); return; }
    const ev: CalEvent = {
      id: `custom-${Date.now()}`,
      title: newEvent.title!,
      description: newEvent.description || "",
      date: newEvent.date!,
      time: newEvent.time,
      type: (newEvent.type as CalEvent["type"]) || "custom",
      url: newEvent.url,
      reminder: false,
    };
    const updated = [ev, ...calEvents].sort((a, b) => b.date.localeCompare(a.date));
    setCalEvents(updated);
    saveCalEvents(updated);
    setNewEvent({ type: "custom", reminder: false });
    setShowAddForm(false);
    toast.success("Event added");
  };

  const deleteCalEvent = (id: string) => {
    const updated = calEvents.filter(e => e.id !== id);
    setCalEvents(updated);
    saveCalEvents(updated);
  };

  /* ─── Derived data ─── */
  const filteredNews = useMemo(() => {
    if (newsFilter === "all") return news;
    if (newsFilter === "featured") return news.filter(n => n.is_featured);
    return news.filter(n => n.sentiment?.toLowerCase() === newsFilter || n.source === newsFilter);
  }, [news, newsFilter]);

  const newsSources = useMemo(() => [...new Set(news.map(n => n.source))].slice(0, 6), [news]);

  const filteredKols = useMemo(() => {
    if (kolFilter === "holdings") return kols.filter(k => (holdings[k.id]?.length ?? 0) > 0);
    if (kolFilter === "buys") {
      const buyerIds = new Set(transactions.filter(t => t.tx_type === "buy").map(t => t.kol_id));
      return kols.filter(k => buyerIds.has(k.id));
    }
    if (kolFilter === "sells") {
      const sellerIds = new Set(transactions.filter(t => t.tx_type === "sell").map(t => t.kol_id));
      return kols.filter(k => sellerIds.has(k.id));
    }
    return kols;
  }, [kols, kolFilter, transactions, holdings]);

  const filteredCal = useMemo(() => {
    const all = calEvents.slice(0, MAX_PER_CATEGORY);
    if (calFilter === "all") return all;
    if (calFilter === "news") return all.filter(e => e.type === "news");
    if (calFilter === "trending") return all.filter(e => e.type === "trending");
    return all.filter(e => !e.autoGenerated);
  }, [calEvents, calFilter]);

  /* ─────────────────────────────────────────────────────────────── */
  /* Render                                                           */
  /* ─────────────────────────────────────────────────────────────── */

  const tabs: { id: Tab; label: string; Icon: React.ElementType; count?: number }[] = [
    { id: "news", label: "News", Icon: Newspaper, count: news.length || undefined },
    { id: "calendar", label: "Calendar", Icon: Calendar, count: calEvents.filter(e => !e.autoGenerated).length || undefined },
  ];

  return (
    <div className="flex flex-col rounded-[1.75rem] border border-white/[0.08] bg-card overflow-hidden">

      {/* ── Header ── */}
      <div className="flex items-center justify-between gap-3 px-4 pt-4 pb-3">
        <div className="flex items-center gap-2.5">
          <div className="flex h-9 w-9 items-center justify-center rounded-xl border border-primary/25 bg-primary/10">
            <Zap className="h-4.5 w-4.5 text-primary" />
          </div>
          <div>
            <h3 className="text-[13px] font-black uppercase tracking-widest text-white">Intel Feed</h3>
            <p className="text-[10px] text-white/35">News · Events · Calendar</p>
          </div>
        </div>
        {/* refresh button */}
        <button
          type="button"
          onClick={() => {
            if (tab === "news") loadNews(true);
            if (tab === "calendar") loadTrending();
          }}
          className="flex h-8 w-8 items-center justify-center rounded-xl border border-white/[0.08] bg-white/[0.03] text-white/40 transition hover:bg-white/[0.07] hover:text-white"
        >
          <RefreshCw className="h-3.5 w-3.5" />
        </button>
      </div>

      {/* ── Tabs ── */}
      <div className="flex gap-1.5 px-4 pb-3">
        {tabs.map(t => (
          <button
            key={t.id}
            type="button"
            onClick={() => setTab(t.id)}
            className={cn(
              "flex items-center gap-1.5 rounded-xl px-3 py-1.5 text-[11px] font-bold transition",
              tab === t.id
                ? "bg-primary/15 text-primary border border-primary/25"
                : "text-white/40 border border-transparent hover:text-white/70 hover:bg-white/[0.04]"
            )}
          >
            <t.Icon className="h-3.5 w-3.5" />
            {t.label}
            {t.count !== undefined && t.count > 0 && (
              <span className={cn(
                "rounded-full px-1.5 py-0.5 text-[9px] font-black",
                tab === t.id ? "bg-primary/20 text-primary" : "bg-white/[0.06] text-white/35"
              )}>
                {t.count}
              </span>
            )}
          </button>
        ))}
      </div>

      {/* ── Panel body — fixed height with inner scroll ── */}
      <div className="flex flex-col flex-1 min-h-0">

        {/* ════ NEWS TAB ════ */}
        {tab === "news" && (
          <>
            {/* filter pills */}
            <div className="flex gap-1.5 px-4 pb-3 overflow-x-auto" style={{ scrollbarWidth: "none" }}>
              {(["all", "featured", "bullish", "bearish", ...newsSources] as string[]).map(f => (
                <button
                  key={f}
                  type="button"
                  onClick={() => setNewsFilter(f)}
                  className={cn(
                    "shrink-0 rounded-lg px-2.5 py-1 text-[10px] font-bold capitalize transition border",
                    newsFilter === f
                      ? "bg-white/10 text-white border-white/20"
                      : "text-white/35 border-transparent hover:text-white/60 hover:border-white/10"
                  )}
                >
                  {f === "all" ? `All (${news.length})` : f}
                </button>
              ))}
            </div>

            {/* scrollable list */}
            <div className="overflow-y-auto px-4 pb-4 space-y-2.5" style={{ maxHeight: 480, scrollbarWidth: "thin" }}>
              {newsLoading ? (
                <div className="flex flex-col items-center gap-3 py-12">
                  <Loader2 className="h-6 w-6 text-primary animate-spin" />
                  <p className="text-[12px] text-white/30">Loading news…</p>
                </div>
              ) : filteredNews.length === 0 ? (
                <div className="flex flex-col items-center gap-3 py-12">
                  <AlertCircle className="h-8 w-8 text-white/15" />
                  <p className="text-[12px] text-white/30">No news yet</p>
                  <button
                    type="button"
                    onClick={() => loadNews(true)}
                    className="flex items-center gap-1.5 rounded-xl border border-white/10 bg-white/5 px-3 py-1.5 text-[11px] font-bold text-white/50 transition hover:bg-white/10 hover:text-white"
                  >
                    <RefreshCw className="h-3 w-3" /> Fetch RSS
                  </button>
                </div>
              ) : (
                filteredNews.map(item => <NewsCard key={item.id} item={item} />)
              )}
            </div>
          </>
        )}


        {/* ════ CALENDAR TAB ════ */}
        {tab === "calendar" && (
          <>
            {/* filter + add row */}
            <div className="flex items-center gap-2 px-4 pb-3">
              <div className="flex gap-1.5 flex-1 overflow-x-auto" style={{ scrollbarWidth: "none" }}>
                {(["all", "trending", "news", "custom"] as CalFilter[]).map(f => (
                  <button
                    key={f}
                    type="button"
                    onClick={() => setCalFilter(f)}
                    className={cn(
                      "shrink-0 rounded-lg px-2.5 py-1 text-[10px] font-bold capitalize transition border",
                      calFilter === f
                        ? "bg-white/10 text-white border-white/20"
                        : "text-white/35 border-transparent hover:text-white/60 hover:border-white/10"
                    )}
                  >
                    {f === "all" ? `All (${calEvents.length})` : f}
                  </button>
                ))}
              </div>
              <button
                type="button"
                onClick={() => setShowAddForm(s => !s)}
                className="shrink-0 flex items-center gap-1 rounded-xl border border-primary/25 bg-primary/10 px-2.5 py-1.5 text-[11px] font-bold text-primary transition hover:bg-primary/20"
              >
                <Plus className="h-3.5 w-3.5" /> Add
              </button>
            </div>

            {/* add form */}
            {showAddForm && (
              <div className="mx-4 mb-3 rounded-[1.1rem] border border-white/[0.08] bg-white/[0.03] p-3.5 space-y-2.5">
                <p className="text-[11px] font-black text-white/50 uppercase tracking-widest">New Event</p>
                <input
                  className="w-full rounded-xl border border-white/[0.08] bg-white/[0.03] px-3 py-2 text-[12px] text-white placeholder-white/25 outline-none focus:border-primary/40"
                  placeholder="Event title *"
                  value={newEvent.title || ""}
                  onChange={e => setNewEvent(s => ({ ...s, title: e.target.value }))}
                />
                <input
                  type="date"
                  className="w-full rounded-xl border border-white/[0.08] bg-white/[0.03] px-3 py-2 text-[12px] text-white outline-none focus:border-primary/40"
                  value={newEvent.date || ""}
                  onChange={e => setNewEvent(s => ({ ...s, date: e.target.value }))}
                />
                <input
                  className="w-full rounded-xl border border-white/[0.08] bg-white/[0.03] px-3 py-2 text-[12px] text-white placeholder-white/25 outline-none focus:border-primary/40"
                  placeholder="Description (optional)"
                  value={newEvent.description || ""}
                  onChange={e => setNewEvent(s => ({ ...s, description: e.target.value }))}
                />
                <select
                  className="w-full rounded-xl border border-white/[0.08] bg-card px-3 py-2 text-[12px] text-white outline-none focus:border-primary/40"
                  value={newEvent.type || "custom"}
                  onChange={e => setNewEvent(s => ({ ...s, type: e.target.value as CalEvent["type"] }))}
                >
                  <option value="launch">🚀 Launch</option>
                  <option value="unlock">🔓 Token Unlock</option>
                  <option value="ama">🎙️ AMA/Space</option>
                  <option value="airdrop">🎁 Airdrop</option>
                  <option value="custom">📌 Custom</option>
                </select>
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={addCalEvent}
                    className="flex-1 rounded-xl bg-primary py-2 text-[12px] font-black text-og-ink transition hover:brightness-110"
                  >
                    Add Event
                  </button>
                  <button
                    type="button"
                    onClick={() => setShowAddForm(false)}
                    className="flex-1 rounded-xl border border-white/10 bg-white/5 py-2 text-[12px] font-bold text-white/50 transition hover:text-white"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            )}

            {/* event list */}
            <div className="overflow-y-auto px-4 pb-4 space-y-2.5" style={{ maxHeight: 440, scrollbarWidth: "thin" }}>
              {calLoading ? (
                <div className="flex items-center justify-center gap-2 py-8">
                  <Loader2 className="h-5 w-5 text-primary animate-spin" />
                  <p className="text-[12px] text-white/30">Loading events…</p>
                </div>
              ) : filteredCal.length === 0 ? (
                <div className="flex flex-col items-center gap-3 py-12">
                  <Calendar className="h-8 w-8 text-white/15" />
                  <p className="text-[12px] text-white/30">No events yet</p>
                  <button
                    type="button"
                    onClick={() => setShowAddForm(true)}
                    className="flex items-center gap-1.5 rounded-xl border border-primary/20 bg-primary/10 px-3 py-1.5 text-[11px] font-bold text-primary transition hover:bg-primary/20"
                  >
                    <Plus className="h-3.5 w-3.5" /> Add first event
                  </button>
                </div>
              ) : (
                filteredCal.map(ev => <CalEventRow key={ev.id} ev={ev} onDelete={deleteCalEvent} />)
              )}
            </div>
          </>
        )}
      </div>
    </div>
  );
}
